###############################################################
#                   Vega init data                            #
###############################################################
# dashboard
Roles:
  - Name: admin
    Label: 超级管理员
    Describe: 超级管理员
    Users:
      - Username: admin
        Nickname: admin
        Password: adminadmin
        Describe: 超级管理员

  - Name: user
    Label: 用户
    Describe: 用户

Permissions:
  -
    Name: dashboard
    Label: 仪表盘
    Describe: 仪表盘
    Icon: safety-certificate
    Path: /dashboard
    Actions:
      - Name: add
        Describe: 新建
        Resources:
          - Method: POST
            Path: /api/dashboard
      - Name: get
        Describe: 查询
        Resources:
          - Method: GET
            Path: /api/dashboard
      - Name: edit
        Describe: 修改
        Resources:
          - Method: GET
            Path: /api/dashboard
          - Method: PUT
            Path: /api/dashboard/:id
      - Name: query
        Describe: 列表
        Resources:
          - Method: GET
            Path: /api/dashboard
      - Name: delete
        Describe: 删除
        Resources:
          - Method: DELETE
            Path: /api/dashboard/:id

  -
    Name: system
    Label: 系统管理
    Describe: 系统管理
    Icon: setting
    Path: /console/system
    Actions:
      - Name: get
        Describe: 查询
        Resources:
          - Method: GET
            Path: /api/console/system
      - Name: edit
        Describe: 修改
        Resources:
          - Method: GET
            Path: /api/console/system
          - Method: PUT
            Path: /api/console/system/:id
      - Name: query
        Describe: 列表
        Resources:
          - Method: GET
            Path: /api/console/system

  -
    Name: system:permission
    Label: 权限管理
    Describe: 权限管理
    Icon: safety-certificate
    Path: /console/system/permissions
    Actions:
      -
        Name: add
        Describe: 新建
        Resources:
          -
            Method: POST
            Path: /api/console/permissions
      -
        Name: get
        Describe: 查询
        Resources:
          -
            Method: GET
            Path: /api/console/permissions
      -
        Name: edit
        Describe: 修改
        Resources:
          -
            Method: GET
            Path: /api/console/permissions
          -
            Method: PUT
            Path: /api/console/permissions/:id
      -
        Name: query
        Describe: 列表
        Resources:
          -
            Method: GET
            Path: /api/console/permissions
      -
        Name: delete
        Describe: 删除
        Resources:
          -
            Method: DELETE
            Path: /api/console/permissions/:id

  -
    Name: system:roles
    Label: 角色管理
    Describe: 角色管理
    Icon: safety-certificate
    Path: /console/system/roles
    Actions:
      -
        Name: add
        Describe: 新建
        Resources:
          -
            Method: POST
            Path: /api/console/roles
      -
        Name: get
        Describe: 查询
        Resources:
          -
            Method: GET
            Path: /api/console/roles
      -
        Name: edit
        Describe: 修改
        Resources:
          -
            Method: GET
            Path: /api/console/roles
          -
            Method: PUT
            Path: /api/console/roles/:id
      -
        Name: query
        Describe: 列表
        Resources:
          -
            Method: GET
            Path: /api/console/roles
      -
        Name: delete
        Describe: 删除
        Resources:
          -
            Method: DELETE
            Path: /api/console/roles/:id

  -
    Name: system:users
    Label: 用户管理
    Describe: 用户管理
    Icon: safety-certificate
    Path: /console/system/users
    Actions:
      -
        Name: add
        Describe: 新建
        Resources:
          -
            Method: POST
            Path: /api/console/users
      -
        Name: get
        Describe: 查询
        Resources:
          -
            Method: GET
            Path: /api/console/users
      -
        Name: edit
        Describe: 修改
        Resources:
          -
            Method: GET
            Path: /api/console/users
          -
            Method: PUT
            Path: /api/console/users/:id
      -
        Name: query
        Describe: 列表
        Resources:
          -
            Method: GET
            Path: /api/console/users
      -
        Name: delete
        Describe: 删除
        Resources:
          -
            Method: DELETE
            Path: /api/console/users/:id
  -
    Name: system:settings
    Label: 系统设置
    Describe: 系统设置
    Icon: safety-certificate
    Path: /console/system/settings
    Actions:
      -
        Name: add
        Describe: 新建
        Resources:
          -
            Method: POST
            Path: /api/console/settings
      -
        Name: get
        Describe: 查询
        Resources:
          -
            Method: GET
            Path: /api/console/settings
      -
        Name: edit
        Describe: 修改
        Resources:
          -
            Method: GET
            Path: /api/console/settings
          -
            Method: PUT
            Path: /api/console/settings/:id
      -
        Name: query
        Describe: 列表
        Resources:
          -
            Method: GET
            Path: /api/console/settings
      -
        Name: delete
        Describe: 删除
        Resources:
          -
            Method: DELETE
            Path: /api/console/settings

  -
    Name: account
    Label: 帐户设置
    Describe: 帐户设置
    Icon: safety-certificate
    Path: /console/account
    Actions:
      -
        Name: add
        Describe: 新建
        Resources:
          -
            Method: POST
            Path: /api/console/account
      -
        Name: get
        Describe: 查询
        Resources:
          -
            Method: GET
            Path: /api/console/account
      -
        Name: edit
        Describe: 修改
        Resources:
          -
            Method: GET
            Path: /api/console/account
          -
            Method: PUT
            Path: /api/console/account/:id
      -
        Name: query
        Describe: 列表
        Resources:
          -
            Method: GET
            Path: /api/console/account
      -
        Name: delete
        Describe: 删除
        Resources:
          -
            Method: DELETE
            Path: /api/console/account/:id
